name: Django tests

on:
    push:
        branches:
            - test

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up python
              uses: actions/setup-python@v2
              with:
                python-version: 3.11
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: run tests
              run: |
                pytest